name = "isokohub"
compatibility_date = "2026-09-08"

[[d1_databases]]
binding = "DB"
database_name = "isokohub-db"
database_id = "AHA_NIHO_USHYIRA_REAL_D1_DATABASE_ID"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "isokohub-images"
